### ISSUE TITLE
Installation is incomplete

### ISSUE THREAD

**Issue by karstenw** [qwesda/fp5dump#1]
OSX 10.6, Python 3.4.3 32-bit intel
After installation on py3.4.3 the library folder 'fp5file' was not installed.

**Comment by qwesda** [comment]
should be fixed now, install log now says:

```
copying build/lib/fp5dump/fp5file/__init__.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/block.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/blockchain.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/datafield.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/exporter.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/fp5file.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/postgresexporter.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
copying build/lib/fp5dump/fp5file/psqlexporter.py -> build/bdist.macosx-10.10-x86_64/egg/fp5dump/fp5file
```

**Comment by karstenw** [comment]
Dang.

A single (m or n) dash in README.md (line 140 col 37):

<pre>kwmbp% python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4630: ordinal not in range(128)
Exit 1</pre>

After replacing it with a simple dash '-' it builds.

**Comment by qwesda** [comment]
can you try it now?

**Comment by karstenw** [comment]
Builds & installs.
