### ISSUE TITLE
Test files with different encodings?

### ISSUE THREAD

**Issue by evanmiller** [qwesda/fp5dump#5]
Hi! I've been working on a C library ([fmptools](https://github.com/evanmiller/fmptools)) to read in FileMaker databases of all vintages. One issue I'm running up against is the text encoding of FP3/FP5 files. A couple of questions:

* Do you know whether there's a field in FP5 indicating the encoding? (And do you know positively if there's NOT such a field?)
* Do you have any test files with known, different encodings? (All of my test files appear to be MacRoman.)

Any tips / pointers appreciated. Thanks!

**Comment by karstenw** [comment]
If I remember correctly...

All versions prior to 7 used MacRoman. That included the windows versions.

The difference between fp3 and fp5 format was just the format string. There was a tiny script back then to back convert fp5 to fp3.

Since V7 UTF-16 is used.

**Comment by evanmiller** [comment]
@karstenw That makes sense. Since fp5dump includes an `--encoding` flag, I thought perhaps other encodings were possible. I'll leave this issue open until there is a definitive answer.

Version 7 and later actually appear to store strings as Standard Compression Scheme for Unicode

https://en.wikipedia.org/wiki/Standard_Compression_Scheme_for_Unicode

The strings look like Latin-1 but can switch to UTF-16 in the middle.

**Comment by qwesda** [comment]
I just did a quick test. It appears that you can set _something_ in the text field options – it's not super clear if it's an **encoding** or a **collation**, my bet is: it's kinda both ...

I appended an example file with one text field for every encoding/collation, I didn't have time to get some sample text for the languages. But you can try to identify the field definition attribute that corresponds to the options.

Do you have access to running a FM5 program to create test files for yourself?

[text_encoding.fp5.zip](https://github.com/qwesda/fp5dump/files/5831684/text_encoding.fp5.zip)

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/384993/104946274-1077ae00-59ba-11eb-9b1d-8b252dc4bc6a.png">

**Comment by evanmiller** [comment]
Thanks, this is helpful! It looks like each field in this file has a different value in the fourth byte of `3/5/NN/2`. I'm guessing that field specifies the collation, since I assume many of these languages will be sharing the MacRoman encoding.

I don't have a copy of FM5 running. I'm on a modern Mac but have an ancient PPC iMac I can fire up if needed.

If you get a chance later probably the most helpful thing would be a version of this file with non-Roman character data (e.g. Greek and Cyrillic). It would also be useful to know if the column names themselves can be non-Roman.

**Comment by qwesda** [comment]
I tried around for a bit, but I couldn't get any cyrillic text in there. 

I think this also makes sense: FM5 is from 1999 and if I remember correctly unicode was still not universally supported and you had to do crazy things to get non-latin text to work. So pasting unicode encoded text won't work – you would need the text in whatever encoding FM5 expects and you probably need a specific font to get it displayed correctly. 

Unless you find someone who has a FP5 file with cyrillic or greek text, you are probably out of luck.

But I don't think the language options would make sense, if you couldn't get the text in there somehow. People wouldn't have entered Russian text in romanised form, right? ... right?

Anyway, the help hasn't much to say about the language option either ...

<img width="720" alt="image" src="https://user-images.githubusercontent.com/384993/104956309-31e19580-59cc-11eb-8aab-96eb2be93cc6.png">

**Comment by evanmiller** [comment]
@qwesda Thanks for the additional research! I guess you would need to set the system / VM locale to Greek or Russian in order to input those characters, then it's not clear how FileMaker would treat them. I think only a file-wide encoding would really make sense. It's also possible Claris started to implement full locale support but just gave up when they knew Unicode was eventually coming.

Anyways, I don't really need this feature for anything, but it seemed like an important loose end. For what it's worth I have documented the collation numbers in the file that you shared here:

https://github.com/evanmiller/fmptools/commit/3fae3f45259bfc1fb222b8d92e32c553e62cd693

Don't know if anyone will need them for anything, but there they are!

I'll go ahead and close this issue since I've received as much of an answer here as I can rightfully expect. Thanks again.

**Comment by qwesda** [comment]
no problem!
